model:
  name: "yolov8n.pt"
  confidence_threshold: 0.25
  iou_threshold: 0.45
  path: "models/yolov8n.pt"

camera:
  width: 640
  height: 480
  fps: 15
  index: 0

resources:
  max_memory_usage: 512MB
  use_gpu: false
  optimize_for_low_spec: true

detection:
  confidence_threshold: 0.25

witch_trigger:
  confidence_threshold: 0.5
  min_interval_sec: 3600
  start_time: "00:00"
  end_time: "05:00"